services:
  - type: web
    name: blood-bank-system
    env: node
    buildCommand: npm install --production=false && npm run build
    startCommand: node server/migrate.js && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blood-bank-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: blood-bank-db
    databaseName: blood_bank
    user: blood_bank_user
    plan: free 
